nn:
  build:
    - ./neuralnet
  links:
    - db
    - data
webscraper:
  build:
    - ./webscraper
  links:
    - db
webapp:
  restart: always
  build:
    - ./webapp
  links: db
nginx:
  restart: always
  build: ./nginx/
  ports:
    - "80:80"
  volumes:
    - /www/public
  volumes_from:
    - web
  links:
    - web:web
db:
  restart: always
  image: mongo:latest
  volumes_from:
    - data
  ports:
    - "5432:5432"
data:
  image: cogniteev/echo
  command: echo 'Data Container for Mongo'
  volumes:
    - data/